// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: dna.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkPpt          *Range         `protobuf:"bytes,1,opt,name=link_ppt,json=linkPpt,proto3" json:"link_ppt,omitempty"`
	Rtt              *Range         `protobuf:"bytes,2,opt,name=rtt,proto3" json:"rtt,omitempty"`
	NumSenders       *Range         `protobuf:"bytes,3,opt,name=num_senders,json=numSenders,proto3" json:"num_senders,omitempty"`
	MeanOffDuration  float32        `protobuf:"fixed32,4,opt,name=mean_off_duration,json=meanOffDuration,proto3" json:"mean_off_duration,omitempty"`
	MeanOnDuration   float32        `protobuf:"fixed32,5,opt,name=mean_on_duration,json=meanOnDuration,proto3" json:"mean_on_duration,omitempty"`
	Generations      uint32         `protobuf:"varint,6,opt,name=generations,proto3" json:"generations,omitempty"`
	WindowIncrements []uint32       `protobuf:"varint,7,rep,packed,name=window_increments,json=windowIncrements,proto3" json:"window_increments,omitempty"`
	WindowMultiples  []float32      `protobuf:"fixed32,8,rep,packed,name=window_multiples,json=windowMultiples,proto3" json:"window_multiples,omitempty"`
	Intersends       []float32      `protobuf:"fixed32,9,rep,packed,name=intersends,proto3" json:"intersends,omitempty"`
	Domains          []*MemoryRange `protobuf:"bytes,10,rep,name=domains,proto3" json:"domains,omitempty"`
}

func (x *ConfigRange) Reset() {
	*x = ConfigRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRange) ProtoMessage() {}

func (x *ConfigRange) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRange.ProtoReflect.Descriptor instead.
func (*ConfigRange) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRange) GetLinkPpt() *Range {
	if x != nil {
		return x.LinkPpt
	}
	return nil
}

func (x *ConfigRange) GetRtt() *Range {
	if x != nil {
		return x.Rtt
	}
	return nil
}

func (x *ConfigRange) GetNumSenders() *Range {
	if x != nil {
		return x.NumSenders
	}
	return nil
}

func (x *ConfigRange) GetMeanOffDuration() float32 {
	if x != nil {
		return x.MeanOffDuration
	}
	return 0
}

func (x *ConfigRange) GetMeanOnDuration() float32 {
	if x != nil {
		return x.MeanOnDuration
	}
	return 0
}

func (x *ConfigRange) GetGenerations() uint32 {
	if x != nil {
		return x.Generations
	}
	return 0
}

func (x *ConfigRange) GetWindowIncrements() []uint32 {
	if x != nil {
		return x.WindowIncrements
	}
	return nil
}

func (x *ConfigRange) GetWindowMultiples() []float32 {
	if x != nil {
		return x.WindowMultiples
	}
	return nil
}

func (x *ConfigRange) GetIntersends() []float32 {
	if x != nil {
		return x.Intersends
	}
	return nil
}

func (x *ConfigRange) GetDomains() []*MemoryRange {
	if x != nil {
		return x.Domains
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Low  float32 `protobuf:"fixed32,1,opt,name=low,proto3" json:"low,omitempty"`
	High float32 `protobuf:"fixed32,2,opt,name=high,proto3" json:"high,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{1}
}

func (x *Range) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Range) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

type Whisker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Generation      uint32       `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	WindowIncrement uint32       `protobuf:"varint,2,opt,name=window_increment,json=windowIncrement,proto3" json:"window_increment,omitempty"`
	WindowMultiple  float32      `protobuf:"fixed32,3,opt,name=window_multiple,json=windowMultiple,proto3" json:"window_multiple,omitempty"`
	Intersend       float32      `protobuf:"fixed32,4,opt,name=intersend,proto3" json:"intersend,omitempty"`
	Domain          *MemoryRange `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
}

func (x *Whisker) Reset() {
	*x = Whisker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Whisker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Whisker) ProtoMessage() {}

func (x *Whisker) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Whisker.ProtoReflect.Descriptor instead.
func (*Whisker) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{2}
}

func (x *Whisker) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Whisker) GetWindowIncrement() uint32 {
	if x != nil {
		return x.WindowIncrement
	}
	return 0
}

func (x *Whisker) GetWindowMultiple() float32 {
	if x != nil {
		return x.WindowMultiple
	}
	return 0
}

func (x *Whisker) GetIntersend() float32 {
	if x != nil {
		return x.Intersend
	}
	return 0
}

func (x *Whisker) GetDomain() *MemoryRange {
	if x != nil {
		return x.Domain
	}
	return nil
}

type MemoryRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lower *Memory `protobuf:"bytes,1,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper *Memory `protobuf:"bytes,2,opt,name=upper,proto3" json:"upper,omitempty"`
}

func (x *MemoryRange) Reset() {
	*x = MemoryRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRange) ProtoMessage() {}

func (x *MemoryRange) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRange.ProtoReflect.Descriptor instead.
func (*MemoryRange) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryRange) GetLower() *Memory {
	if x != nil {
		return x.Lower
	}
	return nil
}

func (x *MemoryRange) GetUpper() *Memory {
	if x != nil {
		return x.Upper
	}
	return nil
}

type Memory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecvRate         float32 `protobuf:"fixed32,1,opt,name=recv_rate,json=recvRate,proto3" json:"recv_rate,omitempty"`
	SendRate         float32 `protobuf:"fixed32,2,opt,name=send_rate,json=sendRate,proto3" json:"send_rate,omitempty"`
	LatestDelay      float32 `protobuf:"fixed32,3,opt,name=latest_delay,json=latestDelay,proto3" json:"latest_delay,omitempty"`
	InterPacketDelay float32 `protobuf:"fixed32,4,opt,name=inter_packet_delay,json=interPacketDelay,proto3" json:"inter_packet_delay,omitempty"`
}

func (x *Memory) Reset() {
	*x = Memory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{4}
}

func (x *Memory) GetRecvRate() float32 {
	if x != nil {
		return x.RecvRate
	}
	return 0
}

func (x *Memory) GetSendRate() float32 {
	if x != nil {
		return x.SendRate
	}
	return 0
}

func (x *Memory) GetLatestDelay() float32 {
	if x != nil {
		return x.LatestDelay
	}
	return 0
}

func (x *Memory) GetInterPacketDelay() float32 {
	if x != nil {
		return x.InterPacketDelay
	}
	return 0
}

type Whiskers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whiskers []*Whisker `protobuf:"bytes,1,rep,name=whiskers,proto3" json:"whiskers,omitempty"`
}

func (x *Whiskers) Reset() {
	*x = Whiskers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dna_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Whiskers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Whiskers) ProtoMessage() {}

func (x *Whiskers) ProtoReflect() protoreflect.Message {
	mi := &file_dna_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Whiskers.ProtoReflect.Descriptor instead.
func (*Whiskers) Descriptor() ([]byte, []int) {
	return file_dna_proto_rawDescGZIP(), []int{5}
}

func (x *Whiskers) GetWhiskers() []*Whisker {
	if x != nil {
		return x.Whiskers
	}
	return nil
}

var File_dna_proto protoreflect.FileDescriptor

var file_dna_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x6e, 0x61,
	0x22, 0x9b, 0x03, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x25, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x70, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07,
	0x6c, 0x69, 0x6e, 0x6b, 0x50, 0x70, 0x74, 0x12, 0x1c, 0x0a, 0x03, 0x72, 0x74, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x03, 0x72, 0x74, 0x74, 0x12, 0x2b, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x6e, 0x61,
	0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x61, 0x6e, 0x5f, 0x6f, 0x66, 0x66, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x6d,
	0x65, 0x61, 0x6e, 0x4f, 0x66, 0x66, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x0a, 0x10, 0x6d, 0x65, 0x61, 0x6e, 0x5f, 0x6f, 0x6e, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x6d, 0x65, 0x61, 0x6e, 0x4f, 0x6e,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x10, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x6e, 0x63,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x5f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x0f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x64, 0x73,
	0x18, 0x09, 0x20, 0x03, 0x28, 0x02, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x6e,
	0x64, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x22, 0x2d,
	0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x22, 0xc5, 0x01,
	0x0a, 0x07, 0x57, 0x68, 0x69, 0x73, 0x6b, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x77, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x6e,
	0x61, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x53, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x52, 0x05, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x75, 0x70, 0x70, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x4d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x52, 0x05, 0x75, 0x70, 0x70, 0x65, 0x72, 0x22, 0x93, 0x01, 0x0a, 0x06, 0x4d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x72, 0x65, 0x63, 0x76, 0x52, 0x61,
	0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x61, 0x79,
	0x22, 0x34, 0x0a, 0x08, 0x57, 0x68, 0x69, 0x73, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x08,
	0x77, 0x68, 0x69, 0x73, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x64, 0x6e, 0x61, 0x2e, 0x57, 0x68, 0x69, 0x73, 0x6b, 0x65, 0x72, 0x52, 0x08, 0x77, 0x68,
	0x69, 0x73, 0x6b, 0x65, 0x72, 0x73, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dna_proto_rawDescOnce sync.Once
	file_dna_proto_rawDescData = file_dna_proto_rawDesc
)

func file_dna_proto_rawDescGZIP() []byte {
	file_dna_proto_rawDescOnce.Do(func() {
		file_dna_proto_rawDescData = protoimpl.X.CompressGZIP(file_dna_proto_rawDescData)
	})
	return file_dna_proto_rawDescData
}

var file_dna_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_dna_proto_goTypes = []interface{}{
	(*ConfigRange)(nil), // 0: dna.ConfigRange
	(*Range)(nil),       // 1: dna.Range
	(*Whisker)(nil),     // 2: dna.Whisker
	(*MemoryRange)(nil), // 3: dna.MemoryRange
	(*Memory)(nil),      // 4: dna.Memory
	(*Whiskers)(nil),    // 5: dna.Whiskers
}
var file_dna_proto_depIdxs = []int32{
	1, // 0: dna.ConfigRange.link_ppt:type_name -> dna.Range
	1, // 1: dna.ConfigRange.rtt:type_name -> dna.Range
	1, // 2: dna.ConfigRange.num_senders:type_name -> dna.Range
	3, // 3: dna.ConfigRange.domains:type_name -> dna.MemoryRange
	3, // 4: dna.Whisker.domain:type_name -> dna.MemoryRange
	4, // 5: dna.MemoryRange.lower:type_name -> dna.Memory
	4, // 6: dna.MemoryRange.upper:type_name -> dna.Memory
	2, // 7: dna.Whiskers.whiskers:type_name -> dna.Whisker
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dna_proto_init() }
func file_dna_proto_init() {
	if File_dna_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dna_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Whisker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dna_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Whiskers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dna_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dna_proto_goTypes,
		DependencyIndexes: file_dna_proto_depIdxs,
		MessageInfos:      file_dna_proto_msgTypes,
	}.Build()
	File_dna_proto = out.File
	file_dna_proto_rawDesc = nil
	file_dna_proto_goTypes = nil
	file_dna_proto_depIdxs = nil
}
